package com.ds.domain.affiliate;


import javax.persistence.*;

/**
 * AffiliateSettings generated by hbm2java
 */
@Entity
@Table(name = "affiliate_settings")
public class AffiliateSettings implements java.io.Serializable {


	@Id
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AFFILIATE_ID", nullable = false)
	private Affiliate affiliate;


	@Column(name = "AFFILIATE_PANEL_ACCESS", nullable = false)
	private Boolean affiliatePanelAccess;


	@Column(name = "FIRE_INITIAL_EMAIL", nullable = false)
	private Boolean fireInitialEmail;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Affiliate getAffiliate() {
		return this.affiliate;
	}

	public void setAffiliate(Affiliate affiliate) {
		this.affiliate = affiliate;
	}

	public Boolean getAffiliatePanelAccess() {
		return this.affiliatePanelAccess;
	}

	public void setAffiliatePanelAccess(Boolean affiliatePanelAccess) {
		this.affiliatePanelAccess = affiliatePanelAccess;
	}

	public Boolean getFireInitialEmail() {
		return this.fireInitialEmail;
	}

	public void setFireInitialEmail(Boolean fireInitialEmail) {
		this.fireInitialEmail = fireInitialEmail;
	}


}


