package com.ds.domain.affiliate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AffiliateGroup generated by hbm2java
 */
@Entity
@Table(name="affiliate_group")
public class AffiliateGroup  implements java.io.Serializable {

    @Id
    @Column(name="ID", unique=true, nullable=false)
    private Long id;
 
    @Column(name="NAME", nullable=false, length=45)
    private String name;
 
    @Column(name="DESCRIPTION", nullable=false, length=65535)
    private String description;
 
    @Column(name="DEFAULT", nullable=false)
    private Boolean isDefault;

    @Column(name="DELETE", nullable=false)
    private Boolean delete;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getIsDefault() {
        return this.isDefault;
    }

    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }
    public Boolean getDelete() {
        return this.delete;
    }

    public void setDelete(Boolean delete) {
        this.delete = delete;
    }




}


