package com.ds.domain.affiliate;
// Generated Oct 19, 2012 1:58:01 AM by Hibernate Tools 3.2.4.CR1


import com.ds.domain.BaseDataObject;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Affiliate generated by hbm2java
 */
@Entity
@Table(name = "AFFILIATE")
public class Affiliate extends BaseDataObject {


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_AFFILIATE_ID")
	private Affiliate parentAffiliate;

	/*@Column(name = "COMPANY_SHORTNAME", nullable = false)
	private String companyShortName;*/

	@Column(name = "LOGIN", nullable = false, length = 45)
	private String login;

	@Column(name = "FIRST_NAME", nullable = false, length = 45)
	private String firstName;

	@Column(name = "LAST_NAME", length = 45)
	private String lastName;

	@Column(name = "EMAIL", length = 45)
	private String email;

	@Column(name = "ADDRESS", length = 90)
	private String address;

	@Column(name = "CITY", length = 45)
	private String city;

	@Column(name = "STATE", length = 45)
	private String state;

	@Column(name = "ZIP", length = 45)
	private String zip;

	@Column(name = "MOBILE", length = 25)
	private String mobile;

	@Column(name = "COMMENTS", length = 65535)
	private String comments;

	@Column(name = "PASSWORD_CHECKSUM", length = 45)
	private String passwordChecksum;

	@Column(name = "DELETED", nullable = false)
	private Boolean deleted;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "affiliate")
	private Set<AffiliateCompany> affiliateCompanies = new HashSet<AffiliateCompany>(0);

/*
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "affiliate")
	private Set<Affiliate> affiliates = new HashSet<Affiliate>(0);
*/

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Affiliate getParentAffiliate() {
		return this.parentAffiliate;
	}

	public void setParentAffiliate(Affiliate parentAffiliate) {
		this.parentAffiliate = parentAffiliate;
	}

	/*public String getCompanyShortName() {
		return companyShortName;
	}

	public void setCompanyShortName(String companyShortName) {
		this.companyShortName = companyShortName;
	}*/

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getPasswordChecksum() {
		return this.passwordChecksum;
	}

	public void setPasswordChecksum(String passwordChecksum) {
		this.passwordChecksum = passwordChecksum;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Set<AffiliateCompany> getAffiliateCompanies() {
		return this.affiliateCompanies;
	}

	public void setAffiliateCompanies(Set<AffiliateCompany> affiliateCompanies) {
		this.affiliateCompanies = affiliateCompanies;
	}

/*
	public Set<Affiliate> getAffiliates() {
		return this.affiliates;
	}

	public void setAffiliates(Set<Affiliate> affiliates) {
		this.affiliates = affiliates;
	}
*/

}


