package com.ds.domain.affiliate;
// Generated Oct 19, 2012 1:58:01 AM by Hibernate Tools 3.2.4.CR1


import com.ds.domain.BaseDataObject;

import javax.persistence.*;

/**
 * AffiliateSetting generated by hbm2java
 */
@Entity
@Table(name = "affiliate_setting")
public class AffiliateSetting extends BaseDataObject {


	@Id
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AFFILIATE_COMPANY_ID", nullable = false)
	private AffiliateCompany affiliateCompany;

	@Column(name = "AFFILIATE_PANEL_ACCESS", nullable = false)
	private Boolean affiliatePanelAccess;

	@Column(name = "FIRE_INITIAL_EMAIL", nullable = false)
	private Boolean fireInitialEmail;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public AffiliateCompany getAffiliateCompany() {
		return this.affiliateCompany;
	}

	public void setAffiliateCompany(AffiliateCompany affiliateCompany) {
		this.affiliateCompany = affiliateCompany;
	}

	public Boolean getAffiliatePanelAccess() {
		return this.affiliatePanelAccess;
	}

	public void setAffiliatePanelAccess(Boolean affiliatePanelAccess) {
		this.affiliatePanelAccess = affiliatePanelAccess;
	}

	public Boolean getFireInitialEmail() {
		return this.fireInitialEmail;
	}

	public void setFireInitialEmail(Boolean fireInitialEmail) {
		this.fireInitialEmail = fireInitialEmail;
	}


}


