package com.ds.domain.affiliate;


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Affiliate generated by hbm2java
 */
@Entity
@Table(name = "affiliate")
public class Affiliate implements java.io.Serializable {


	@Id

	@Column(name = "ID", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_AFFILIATE_ID", nullable = false)
	private Affiliate parentAffiliate;


	@Column(name = "COMPANY_ID", nullable = false)
	private Long companyId;


	@Column(name = "FIRST_NAME", length = 45)
	private String firstName;


	@Column(name = "LAST_NAME", length = 45)
	private String lastName;


	@Column(name = "EMAIL", length = 45)
	private String email;


	@Column(name = "ADDRESS", length = 45)
	private String address;


	@Column(name = "CITY", length = 45)
	private String city;


	@Column(name = "STATE", length = 45)
	private String state;


	@Column(name = "ZIP", length = 45)
	private String zip;


	@Column(name = "MOBILE", length = 45)
	private String mobile;


	@Column(name = "COMMENTS", length = 65535)
	private String comments;


	@Column(name = "PASSWORD_CHECKSUM", length = 45)
	private String passwordChecksum;


	@Column(name = "DELETED", nullable = false)
	private Boolean deleted;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "affiliate")
	private Set<AffiliateSettings> affiliateSettingses = new HashSet<AffiliateSettings>(0);

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Affiliate getAffiliate() {
		return this.parentAffiliate;
	}

	public void setAffiliate(Affiliate parentAffiliate) {
		this.parentAffiliate = parentAffiliate;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getPasswordChecksum() {
		return this.passwordChecksum;
	}

	public void setPasswordChecksum(String passwordChecksum) {
		this.passwordChecksum = passwordChecksum;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Set<AffiliateSettings> getAffiliateSettingses() {
		return this.affiliateSettingses;
	}

	public void setAffiliateSettingses(Set<AffiliateSettings> affiliateSettingses) {
		this.affiliateSettingses = affiliateSettingses;
	}


}


