package com.ds.domain.affiliate;
// Generated Oct 19, 2012 1:58:01 AM by Hibernate Tools 3.2.4.CR1


import com.ds.domain.BaseDataObject;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CommissionPlan generated by hbm2java
 */
@Entity
@Table(name = "commission_plan")
public class CommissionPlan extends BaseDataObject {


	@Id
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;

	@Column(name = "PLAN_NAME", nullable = false, length = 45)
	private String planName;

	/*@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "commissionPlan")
	private Set<AffiliateCompanyCommissionPlan> affiliateCompanyCommissionPlans = new HashSet<AffiliateCompanyCommissionPlan>(0);*/
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPlanName() {
		return this.planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

/*
	public Set<AffiliateCompanyCommissionPlan> getAffiliateCompanyCommissionPlans() {
		return this.affiliateCompanyCommissionPlans;
	}

	public void setAffiliateCompanyCommissionPlans(Set<AffiliateCompanyCommissionPlan> affiliateCompanyCommissionPlans) {
		this.affiliateCompanyCommissionPlans = affiliateCompanyCommissionPlans;
	}
*/


}


