package com.ds.domain.affiliate;
// Generated Oct 19, 2012 1:58:01 AM by Hibernate Tools 3.2.4.CR1


import com.ds.domain.BaseDataObject;

import javax.persistence.*;
import java.util.List;
import java.util.ArrayList;

/**
 * AffiliateGroup generated by hbm2java
 */
@Entity
@Table(name = "company_affiliate_group")
public class CompanyAffiliateGroup extends BaseDataObject {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;

	@Column(name = "COMPANY_SHORTNAME", nullable = false)
	private String companyShortName;

	@Column(name = "NAME", nullable = false, length = 45)
	private String name;

	@Column(name = "DESCRIPTION", nullable = false)
	private String description;

	@Column(name = "DEFAULT_GROUP", nullable = false)
	private Boolean defaultGroup;

	@Column(name = "DELETED", nullable = false)
	private Boolean deleted;

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinTable(name = "com_aff_grp_com_aff",  joinColumns = {
			@JoinColumn(name = "AFFILIATE_GROUP_ID", nullable = false, updatable = false)}, inverseJoinColumns = {
			@JoinColumn(name = "COMPANY_AFFILIATE_ID", nullable = false, updatable = false)})
	private List<CompanyAffiliate> companyAffiliates = new ArrayList<CompanyAffiliate>();


	public Long getId() {                                               
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCompanyShortName() {
		return companyShortName;
	}

	public void setCompanyShortName(String companyShortName) {
		this.companyShortName = companyShortName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getDefaultGroup() {
		return this.defaultGroup;
	}

	public void setDefaultGroup(Boolean defaultGroup) {
		this.defaultGroup = defaultGroup;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public List<CompanyAffiliate> getCompanyAffiliates() {
		return companyAffiliates;
	}

	public void setCompanyAffiliates(List<CompanyAffiliate> companyAffiliates) {
		this.companyAffiliates = companyAffiliates;
	}

}


