package com.ds.domain.affiliate;
// Generated Oct 19, 2012 1:58:01 AM by Hibernate Tools 3.2.4.CR1


import com.ds.domain.BaseDataObject;

import javax.persistence.*;

/**
 * AffiliateCompany generated by hbm2java
 */
@Entity
@Table(name = "company_affiliate")
public class CompanyAffiliate extends BaseDataObject {


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AFFILIATE_ID", nullable = false)
	private Affiliate affiliate;

	@Column(name = "COMPANY_SHORTNAME", nullable = false)
	private String companyShortName;

	@Column(name = "ACTIVE", nullable = false)
	private Boolean active = false;


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_COMPANY_AFFILIATE_ID", nullable = true)
	private CompanyAffiliate parentCompanyAffiliate;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Affiliate getAffiliate() {
		return this.affiliate;
	}

	public void setAffiliate(Affiliate affiliate) {
		this.affiliate = affiliate;
	}

	public String getCompanyShortName() {
		return companyShortName;
	}

	public void setCompanyShortName(String companyShortName) {
		this.companyShortName = companyShortName;
	}

/*
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}
*/

	public CompanyAffiliate getParentCompanyAffiliate() {
		return parentCompanyAffiliate;
	}

	public void setParentCompanyAffiliate(CompanyAffiliate parentCompanyAffiliate) {
		this.parentCompanyAffiliate = parentCompanyAffiliate;
	}
}


