package com.ds.domain.commission;
// Generated Nov 9, 2012 10:22:42 PM by Hibernate Tools 3.2.4.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CommissionCurrency generated by hbm2java
 */
@Entity
@Table(name="commission_currency")
public class CommissionCurrency  implements java.io.Serializable {


 
    @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    private Long id;
 
    
    @Column(name="CURR_CODE", nullable=false, length=45)
    private String currCode;
 
    
    @Column(name="NAME", nullable=false, length=100)
    private String name;
 
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="commissionCurrency")
    private Set<CommissionPlan> commissionPlans = new HashSet<CommissionPlan>(0);
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getCurrCode() {
        return this.currCode;
    }
    
    public void setCurrCode(String currCode) {
        this.currCode = currCode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<CommissionPlan> getCommissionPlans() {
        return this.commissionPlans;
    }
    
    public void setCommissionPlans(Set<CommissionPlan> commissionPlans) {
        this.commissionPlans = commissionPlans;
    }




}


