package com.ds.domain.commission;
// Generated Nov 9, 2012 10:22:42 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CommissionStrategy generated by hbm2java
 */
@Entity
@Table(name="commission_strategy")
public class CommissionStrategy  implements java.io.Serializable {


 
    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", unique=true, nullable=false)
    private Long id;
 
    
    @Column(name="NAME", nullable=false, length=200)
    private String name;
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


